import Vue from 'vue'
import { Button, Card, Form, FormItem, Input, Notification, Message, Container, Header, Aside, Main, Menu, Submenu, MenuItemGroup, MenuItem, Table, TableColumn, Switch, Row, Col, Tooltip, Breadcrumb, BreadcrumbItem, Checkbox, Pagination, Avatar, Dropdown, DropdownMenu, DropdownItem, Dialog, Select, Option, Cascader, Tag } from 'element-ui'
Vue.use(Button)
Vue.use(Card)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Row)
Vue.use(Col)
Vue.use(Tooltip)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Checkbox)
Vue.use(Pagination)
Vue.use(Avatar)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Dialog)
Vue.use(Select)
Vue.use(Option)
Vue.use(Cascader)
Vue.use(Tag)
Vue.prototype.$notify = Notification
Vue.prototype.$message = Message